runner:
  total_steps: 10000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 10
  eval_step: 100
  save_step: 100
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-5

downstream_expert:
  datarc:
    speech_commands_root: /groups/public/benchmark/speech_commands/train
    speech_commands_test_root: /groups/public/benchmark/speech_commands/test
    num_workers: 8
    batch_size: 512

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling

